global:
  edition: ce
  psql:
    host: 192.168.100.35
    database: gitlabhq_production
    username: gitlab
    password:
      secret: postgres-password
      key: password
  hosts:
    domain: gitlab.pereslegin.ru
    https: true
    gitlab:
      name: gitlab.pereslegin.ru
      https: true
    registry:
      name: registry.pereslegin.ru
      https: true
    minio:
      name: minio.pereslegin.ru
      https: true
  shell:
    port: 22
  ingress:
    class: nginx
    tls:
      secretName: gitlab-tls-secret
    annotations:
      kubernetes.io/tls-acme: true
      cert-manager.io/cluster-issuer: letsencrypt
    configureCertmanager: false
  grafana:
    enabled: false
  appConfig:
    backups:
      bucket: gitlab-backup
      tmpBucket: gitlab-tmp
    omniauth:
      enabled: true
      autoSignInWithProvider: openid_connect
      syncProfileFromProvider: [ ]
      syncProfileAttributes: [ 'email' ]
      allowSingleSignOn: true
      blockAutoCreatedUsers: true
      autoLinkLdapUser: false
      autoLinkSamlUser: false
      autoLinkUser: true
      externalProviders: [ ]
      allowBypassTwoFactor: [ ]
      providers:
        - secret: gitlab-keycloak-oidc
certmanager:
  install: false
certmanager-issuer:
  cert-manager.io/cluster-issuer: letsencrypt
  email: dmitry@pereslegin.ru
gitlab-runner:
  install: true
  runners:
    privileged: true
    config: |
      [[runners]]
        [runners.kubernetes]
          image = "ubuntu:22.04"
          privileged = true
        [runners.cache]
          Type = "s3"
          Path = "runner"
          Shared = true
          [runners.cache.s3]
            ServerAddress = {{ include "gitlab-runner.cache-tpl.s3ServerAddress" . }}
            BucketName = "runner-cache"
            BucketLocation = "us-east-1"
            Insecure = false
            AuthenticationType = "access-key"
    cache:
      secretName: gitlab-minio-secret
gitlab-exporter:
  enabled: false
  metrics:
    enabled: false
nginx-ingress:
  enabled: false
minio:
  ingress:
    tls:
      secretName: gitlab-minio-secret
  persistence:
    storageClass: gitlab-minio
    size: 200Gi
redis:
  cluster:
    enabled: false
  master:
    persistence:
      storageClass: gitlab-redis
  metrics:
    enabled: false
gitlab:
  gitaly:
    persistence:
      enabled: true
      storageClass: gitlab-repo
  webservice:
    ingress:
      tls:
        secretName: gitlab-gitlab-tls
    replicaCount: 1
    workerProcesses: 2
    minReplicas: 1
    maxReplicas: 3
  gitlab-shell:
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 3
  toolbox:
    backups:
      cron:
        enabled: true
        concurrencyPolicy: Forbid
        failedJobsHistoryLimit: 1
        schedule: "0 5 * * *"
        startingDeadlineSeconds: null
        successfulJobsHistoryLimit: 3
        suspend: false
        extraArgs: ""
      objectStorage:
        backend: s3
        config:
          secret: gitlab-s3-backup
          key: config
postgresql:
  install: false
  enabled: true
  replication:
    enabled: false
  persistence:
    storageClass: gitlab-postgresql
  metrics:
    enabled: false
prometheus:
  install: false
  server:
    persistentVolume:
      storageClass: gitlab-prometheus
      size: 500Gi
registry:
  ingress:
    tls:
      secretName: gitlab-registry-secret
  hpa:
    minReplicas: 1
    maxReplicas: 3
