dbchecker:
  enabled: true

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"

database:
  vendor: postgres
  hostname: 192.168.100.35
  port: 5432
  database: keycloak

http:
  relativePath: "/auth/"

serviceMonitor:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

proxy:
  enabled: true
  mode: xforwarded
  http:
    enabled: true

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  rules:
    - host: 'auth.wheelsage.org'
      paths:
        - path: /auth/
          pathType: Prefix
    - host: 'auth.pereslegin.ru'
      paths:
        - path: /auth/
          pathType: Prefix
  tls:
    - hosts:
        - auth.wheelsage.org
        - auth.pereslegin.ru
      secretName: keycloak-tls

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "4Gi"
    cpu: "2000m"

metrics:
  enabled: true
