proxy: edge
production: true
httpRelativePath: "/auth/"
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "4Gi"
    cpu: "2000m"

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: auth.pereslegin.ru
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls: true
  extraHosts:
    - name: auth.wheelsage.org
      path: /
  extraTls:
    - hosts:
      - auth.wheelsage.org
      secretName: auth.wheelsage.org-tls

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

postgresql:
  enabled: false

externalDatabase:
  host: "192.168.100.38"
  port: 5432
  database: keycloak
