proxyHeaders: xforwarded
production: true
httpRelativePath: "/auth/"
replicaCount: 1
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "4Gi"
    cpu: "2000m"

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: auth.wheelsage.org
  hostnameStrict: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls: true
  extraHosts:
    - name: auth.pereslegin.ru
      path: /
  extraTls:
    - hosts:
      - auth.pereslegin.ru
      secretName: auth.pereslegin.ru-tls

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

postgresql:
  enabled: false

externalDatabase:
  host: "192.168.100.35"
  port: 5432
  database: keycloak
