kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus
spec:
  capacity:
    storage: 500Gi
  local:
    path: /data/prometheus
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i38
