apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentry-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  local:
    path: /root/k8s-pv/sentry/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i38
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sentry-data
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentry-clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  local:
    path: /root/k8s-pv/sentry/clickhouse
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i38
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sentry-clickhouse
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentry-zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  local:
    path: /root/k8s-pv/sentry/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i38
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sentry-zookeeper
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentry-kafka
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  local:
    path: /root/k8s-pv/sentry/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i38
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sentry-kafka
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentry-rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  local:
    path: /root/k8s-pv/sentry/rabbitmq
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i38
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sentry-rabbitmq
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentry-redis
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  local:
    path: /root/k8s-pv/sentry/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i38
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sentry-redis
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentry-redis
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  local:
    path: /root/k8s-pv/sentry/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i38
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sentry-redis
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentry-clickhouse-zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  local:
    path: /root/k8s-pv/sentry/clickhouse-zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i38
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sentry-clickhouse-zookeeper
  volumeMode: Filesystem
