mysql:
  enabled: true
  architecture: standalone
  auth:
    database: database
    username: username
    password: password
    rootPassword: password
  primary:
    livenessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 1
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mysql
      plugin_dir=/opt/bitnami/mysql/lib/plugin
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      datadir=/bitnami/mysql/data
      tmpdir=/opt/bitnami/mysql/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      log-error=/opt/bitnami/mysql/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      default-time-zone='UTC'
      tmp_table_size=2G
      max_heap_table_size=2G
      max_connections = 2000
      innodb_buffer_pool_size=20G
      innodb_log_file_size = 2G
      innodb_buffer_pool_instances = 16
      [client]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mysql/lib/plugin
      [manager]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    persistence:
      enabled: true
      storageClass: mysql
      size: 100Gi
    resources:
      limits:
        cpu: 5
        ephemeral-storage: 100Gi
        memory: 30Gi
    extraPorts:
      - name: host-port
        hostPort: 3306
        containerPort: 3306
        hostIP: 127.0.0.1
        protocol: TCP
  secondary:
    replicaCount: 0
  metrics:
    enabled: true
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
      initialDelaySeconds: 120
      periodSeconds: 100
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 30
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
    extraArgs:
      primary:
        - --collect.auto_increment.columns
        - --collect.binlog_size
        - --collect.engine_innodb_status
        - --no-collect.engine_tokudb_status
        - --collect.global_status
        - --collect.global_variables
        - --collect.info_schema.clientstats
        - --collect.info_schema.innodb_metrics
        - --collect.info_schema.innodb_tablespaces
        - --collect.info_schema.innodb_cmp
        - --collect.info_schema.innodb_cmpmem
        - --collect.info_schema.processlist
        #- --collect.info_schema.processlist.min_time
        - --collect.info_schema.query_response_time
        - --collect.info_schema.tables
        #- --collect.info_schema.tables.databases
        - --collect.info_schema.tablestats
        - --collect.info_schema.userstats
        - --collect.perf_schema.eventsstatements
        #- --collect.perf_schema.eventsstatements.digest_text_limit
        #- --collect.perf_schema.eventsstatements.limit
        #- --collect.perf_schema.eventsstatements.timelimit
        - --collect.perf_schema.eventswaits
        - --collect.perf_schema.file_events
        - --collect.perf_schema.file_instances
        - --collect.perf_schema.indexiowaits
        - --collect.perf_schema.tableiowaits
        - --collect.perf_schema.tablelocks
        - --collect.perf_schema.replication_group_member_stats
        - --no-collect.slave_status
        - --no-collect.slave_hosts
        #- --collect.heartbeat
        #- --collect.heartbeat.database
        #- --collect.heartbeat.table

backup:
  s3Hostname: "s3.example.com"
  s3AccessKey: "key"
  s3Secret: "secret"
  s3Bucket: "bucket"
  mysqlDatabases:
    - name: autowp
      schedule: "30 5 * * *"
    - name: furygoose
      schedule: "30 4 * * *"

