mysql:
  enabled: true
  architecture: standalone
  auth:
    database: database
    username: username
    password: password
    rootPassword: password
  primary:
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mysql
      plugin_dir=/opt/bitnami/mysql/lib/plugin
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      datadir=/bitnami/mysql/data
      tmpdir=/opt/bitnami/mysql/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      log-error=/opt/bitnami/mysql/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      default-time-zone='UTC'
      tmp_table_size=2G
      max_heap_table_size=2G
      max_connections = 2000
      innodb_buffer_pool_size=20G
      [client]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mysql/lib/plugin
      [manager]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    persistence:
      enabled: true
      storageClass: mysql
      size: 100Gi
    resources:
      limits:
        cpu: 5
        ephemeral-storage: 100Gi
        memory: 30Gi
    extraPorts:
      - name: host-port
        hostPort: 3306
        containerPort: 3306
        hostIP: 127.0.0.1
        protocol: TCP
  secondary:
    replicaCount: 0
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack

backup:
  s3Hostname: "s3.example.com"
  s3AccessKey: "key"
  s3Secret: "secret"
  s3Bucket: "bucket"
  mysqlDatabases:
    - name: autowp
      schedule: "30 5 * * *"
    - name: furygoose
      schedule: "30 4 * * *"

