kind: Secret
apiVersion: v1
metadata:
  name: gitlab-keycloak-oidc
stringData:
  provider: |
    name: 'openid_connect'
    label: 'Keycloak'
    args:
      name: openid_connect
      scope: [ 'openid', 'profile', 'email' ]
      response_type: code
      issuer: {{ .Values.oidc.issuer | quote }}
      client_auth_method: 'query'
      discovery: true
      uid_field: 'preferred_username'
      client_options:
        identifier: {{ .Values.oidc.clientID | quote }}
        secret: {{ .Values.oidc.clientSecret | quote }}
        redirect_uri: {{ .Values.oidc.redirectUri | quote }}
type: Opaque
