kind: Secret
apiVersion: v1
metadata:
  name: gitlab-s3-backup
stringData:
  config: |
    [default]
    access_key = {{ .Values.backup.s3.accessKey }}
    bucket_location = US
    check_ssl_certificate = True
    check_ssl_hostname = True
    connection_pooling = True
    default_mime_type = binary/octet-stream
    delay_updates = False
    delete_after = False
    delete_after_fetch = False
    delete_removed = False
    dry_run = False
    enable_multipart = True
    encoding = UTF-8
    encrypt = False
    follow_symlinks = False
    force = False
    get_continue = False
    gpg_command = /usr/bin/gpg
    gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
    gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
    guess_mime_type = True
    host_base = {{ .Values.backup.s3.host }}
    host_bucket = {{ .Values.backup.s3.host }}/%(bucket)
    human_readable_sizes = False
    invalidate_default_index_on_cf = False
    invalidate_default_index_root_on_cf = True
    invalidate_on_cf = False
    list_md5 = False
    log_target_prefix =
    long_listing = False
    max_delete = -1
    multipart_chunk_size_mb = 15
    multipart_max_chunks = 10000
    preserve_attrs = True
    progress_meter = True
    public_url_use_https = False
    put_continue = False
    recursive = False
    recv_chunk = 4096
    reduced_redundancy = False
    requester_pays = False
    restore_days = 1
    restore_priority = Standard
    secret_key = {{ .Values.backup.s3.secretKey }}
    send_chunk = 4096
    server_side_encryption = False
    signature_v2 = False
    signurl_use_https = False
    simpledb_host = sdb.amazonaws.com
    skip_existing = False
    socket_timeout = 300
    stats = False
    stop_on_error = False
    throttle_max = 100
    urlencoding_mode = normal
    use_http_expect = False
    use_https = True
    use_mime_magic = True
    verbosity = WARNING
    website_endpoint = https://{{ .Values.backup.s3.host }}/%(bucket)
type: Opaque
