kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "metrics"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.hostname | quote }}
      secretName: tls
  rules:
    - host: {{ .Values.hostname | quote }}
      http:
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: kube-state-metrics
                port:
                  name: http

---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: basic-auth
stringData:
  auth: {{ htpasswd .Values.username .Values.password }}
